### ISSUE TITLE
The legends of the graphs in the slides

### ISSUE THREAD

**Issue by yuhengd** [neophenix/StateOfTheMQ#1]
Hi, Can I know what is the metrics for the graphs in the slides, on the y axis? Is it the latency in ms? Thanks.

**Comment by neophenix** [comment]
I _think_ the left is CPU and the right is memory, but I am not certain anymore, and I forget which lines represent what.  These are so outdated I wouldn't use them at all anyway, each project has come a long way since these benchmarks were done.
